easy_admin:
    site_name: En première ligne

    design:
        menu:
            - { route: 'homepage', label: 'Back to the website', icon: 'home' }
            - { route: 'security_logout', label: 'Log out', icon: 'sign-out' }

            - { label: 'Matches' }
            - { route: 'admin_statistics', label: 'Statistics', icon: 'chart-bar' }
            - { route: 'admin_matches', label: 'Matches', icon: 'check' }
            - { route: 'admin_match_history', label: 'History', icon: 'history' }

            - { label: 'Raw data' }
            - { entity: 'Helper', label: 'Helpers', icon: 'users' }
            - { entity: 'HelpRequest', label: 'Help requests', icon: 'handshake-o' }

    entities:
        Helper:
            class: App\Entity\Helper
            disabled_actions: ['show', 'new', 'edit', 'delete']
            list:
                title: Helpers
                max_results: 100
                sort: ['createdAt', 'DESC']
                fields:
                    - id
                    - zipCode
                    - { property: 'incompleteName', label: 'Name' }
                    - canBabysit
                    - canBuyGroceries
                    - createdAt

        HelpRequest:
            class: App\Entity\HelpRequest
            disabled_actions: ['show', 'new', 'edit', 'delete']
            list:
                title: Help requests
                max_results: 100
                sort: ['createdAt', 'DESC']
                fields:
                    - id
                    - zipCode
                    - helpType
                    - { property: 'incompleteName', label: 'Name' }
                    - { property: 'isMatched', type: 'boolean', label: 'Has a match?' }
                    - finished
                    - createdAt
